# Generated by Django 5.2.17 on 2026-09-30 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand_name', models.CharField(default='Prestige Champagne', max_length=100)),
                ('city', models.CharField(default='Kinshasa', max_length=100)),
                ('coffret_image', models.ImageField(blank=True, null=True, upload_to='coffrets/')),
                ('contact_email', models.EmailField(blank=True, max_length=254)),
                ('whatsapp_number', models.CharField(blank=True, max_length=30)),
            ],
        ),
    ]
