# Generated by Django 5.2.17 on 2026-10-05 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PrestigeEmpire', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=140, verbose_name='titre')),
                ('video', models.FileField(upload_to='videos/', verbose_name='fichier vidéo')),
                ('is_published', models.BooleanField(default=True, verbose_name='publiée sur le site')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='ajoutée le')),
            ],
            options={
                'verbose_name': 'Vidéo',
                'verbose_name_plural': 'Vidéos',
                'ordering': ['-created_at'],
            },
        ),
    ]
